smartcontractkit/chainlink-github-actions

chainlink-testing-framework/build-image/action.yml

Changing this from a reusable workflow to an action during the migration opens us up to use more of the github `environment` settings that are being setup.

Move build-custom.yml reusable workflow from chainlink repo as an action

---

chainlink-testing-framework/build-image/action.yml

This was a remnant from when it was originally a workflow and had two different ways to call the workflow. As an action it just gets called as an action and thus is not needed.

Remove duplicate `go gets`

---

chainlink-testing-framework/cleanup/action.yml
chainlink-testing-framework/run-tests/action.yml

Use cases:
1. If the tests spin up resources under the namespace but somehow die unexpectedly and gingko can't clean it up. The cleanup is added to the end of the run-tests to clean it up.
2. If we use gha concurrency to clean up jobs running on previous pr commits that are in progress they will not properly cleanup. We can add the cleanup at the workflow level to properly clean this up since they will not be hard cancelled like they are at the action level. The action level `if: always()` does not propagate through a cancel whereas a workflow level one does. It is a bit wonky.

Add cleanup action

---

chainlink-testing-framework/cleanup/action.yml

Sometimes things are cancelled before kubernetes is setup which can cause errors

Add check for kubectl error so we don't fail on later steps

---

chainlink-testing-framework/build-image/action.yml

I've added this in preparation for https://github.com/smartcontractkit/chainlink/pull/7361.
Since the `build-image` composite action calls `checkout`, I can't pre-emptively fetch the operator-ui static assets before this composite action is called, since any changes within the git directory are wiped.

Add operator ui installation step to docker build

---

chainlink-testing-framework/build-image/action.yml
chainlink-testing-framework/run-tests/action.yml
chainlink-testing-framework/setup-run-tests-environment/action.yml

This means it can pull the latest patch version even when we haven't updated our .tool-versions yet. Basically less upkeep on our end.

Use go.mod for setup-go action instead of .tool-versions

---

CODEOWNERS
docker/build-push/action.yml

This push action wraps docker/build-push-action with the required aws login steps for ecr.

QA-138 Part 1 Add generic docker push action

---

chainlink-testing-framework/build-image/action.yml

The operator-ui is installed as part of the docker image build now.
See https://github.com/smartcontractkit/chainlink/pull/7785

Remove un-needed operator-ui install

---

chainlink-testing-framework/build-image/action.yml
chainlink-testing-framework/run-tests/action.yml
chainlink-testing-framework/setup-run-tests-environment/action.yml
docker/build-push/action.yml

QA-78 Cleanup node 12 and save-state warnings

---

chainlink-testing-framework/run-tests/action.yml
chainlink-testing-framework/setup-run-tests-environment/action.yml

We have projects that need the extra aws registry login as part of the setup and also a need to not run the setup.

Aws registry login for tests

---

chainlink-testing-framework/setup-go/action.yml

Reverts smartcontractkit/chainlink-github-actions#122
This should have not been done. cache_restore_only can be used to not use a cache or we can add an input instead to choose to not cache. Removing the caching from this will cause lots of problems in other pipelines
In addition to the revert I also added the no_cache input to just avoid running the cache if that is needed.

Revert "remove cache from setup-go action"

---

.github/workflows/check-dist.yaml

Tested all actions locally with node `20.8.1`.  This workflow is ran as part of pull requests, so it should be validated there as well.

Update check-dist workflow to use node20

---

chainlink-testing-framework/build-image/action.yml
chainlink-testing-framework/setup-run-tests-environment/action.yml
docker/build-push/action.yml
docker/image-exists/action.yml

Found some action references which need to be updated so the transitive dependency will use node20 instead of node16.
---
[RE-2021](https://smartcontract-it.atlassian.net/browse/RE-2021)

[RE-2021] bump action references

---

utils/wait-for-workflows/action.yml

Updating https://github.com/actions/github-script to `v7.0.0` - https://github.com/actions/github-script/releases/tag/v7.0.0 to use `node20` runner.
This action actually does live in the `.github` repository ([link](https://github.com/smartcontractkit/.github/tree/main/actions/wait-for-workflows)), although some references still exist to this action. [These references](https://github.com/search?q=org%3Asmartcontractkit+uses%3A+chainlink-github-actions%2Futil&type=code) should be migrated eventually, likely as part of [RE-2003](https://smartcontract-it.atlassian.net/browse/RE-2003).
---
[RE-1882](https://smartcontract-it.atlassian.net/browse/RE-1882)

[RE-1882] chore: bump actions/github-script from 6 to 7

---

chainlink-testing-framework/build-tests/action.yml

Now one more argument can be passed to the action: `go_tags` and if it's present we will build the test binary with given tags.

Allow to build test binary with tags

---

chainlink-testing-framework/build-image/action.yml
chainlink-testing-framework/build-tests/action.yml
chainlink-testing-framework/run-tests-binary/action.yml
chainlink-testing-framework/run-tests/action.yml
chainlink-testing-framework/setup-go/action.yml
chainlink-testing-framework/setup-run-tests-environment/action.yml
helm-version-bump/receiver/action.yml

This PR bumps and pins some github actions references:
- `actions/setup-go` from v3/v4 to v5.0.0
- Explicitly disable caching for the v3 reference as that is the major change from v3 -> v4 (caching enabled by default)
- `actions/cache` and `actions/cache/restore` from v3 to v4.0.0
- Updates runtime to `node20` 
- `peter-evans/create-pull-request` from v5.0.1 to v6.0.0
- Updates runtime to `node20` and changes default author
Bump internal references to `v2.3.5` - tag to be created once merged.

chore: github actions version bumps

---

.github/workflows/check-dist.yaml
.github/workflows/cleanup-test.yaml
.github/workflows/go-test-results-parsing-ci.yaml
.github/workflows/mod-version-test.yaml
.github/workflows/semver-compare-ci.yaml
chainlink-testing-framework/build-image/action.yml
chainlink-testing-framework/build-tests/action.yml
chainlink-testing-framework/run-tests-binary/action.yml
chainlink-testing-framework/run-tests/action.yml
chainlink-testing-framework/setup-go/action.yml
chainlink-testing-framework/setup-run-tests-environment/action.yml
docker/build-push/action.yml

External Action Version Bumps:
* bump and pin actions/setup-node to v4.0.2
* bump and pin docker/build-push-action to v5.1.0
* provenance attestation enabled by default (disabled in workflow)
* node20 
* bump and pin docker/setup-buildx-action to v3.1.0
* node20 
* bump and pin references to actions/checkout to v4.1.1
* bump azure setup-helm and k8s-set-context to v4.0.0
* node20
* bump and pin GoTestTools/gotestfmt-action to v2.2.0
* node20
Other Changes:
* bump internal action references to v2.3.7
* update setup-go action name
* the name referenced in the yaml was copied from another action

chore: github action version bumps

---

release/release-tag-check/README.md
release/release-tag-check/action.yml
release/release-tag-check/scripts/releasetagcheck.sh
release/release-tag-check/scripts/releasetagcheck.test.sh

To be used in https://github.com/smartcontractkit/chainlink/pull/12102.
We need the version that a tag is referencing to be able to properly update the version in package.json, this adds the ability to the already used release tag check.
Note: This is backwards compatible and should not break any existing use-cases.
Other changes:
- Added some basic unit testing
- Added readme

feat: releasetagcheck with version output

---

.github/workflows/sync-github-app-token-issuer.yaml

Bumping `push-gha-metrics-action` and pass grafana org-id inputs  
---
RE-2240

chore: grafana internal credentials

---

chainlink-testing-framework/build-tests/action.yml
chainlink-testing-framework/run-tests-binary/action.yml
chainlink-testing-framework/run-tests/action.yml

@Tofel found some problems in the [chainlink/Client Compatibility Tests](https://github.com/smartcontractkit/chainlink/actions/runs/8385969928).
These errors are a problem because an artifact was uploaded through `actions/upload-artifact@v3` and trying to be fetched using `actions/download-artifact@v4`.
These versions are incompatible ([source](https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/)):
> Artifacts v4 is not cross-compatible with previous versions. For example, an artifact uploaded using v3 cannot be used with actions/download-artifact@v4.
I'm bumping the versions here, creating a release, then I will bump the referenced versions in chainlink repository.

chore: bump upload/download artifact action

---

chainlink-testing-framework/run-tests/action.yml

Leaving gotestfmt for now until we get all the uses of it removed so we don't break pipelines in the mean time.

[TT-1016] Add gotestloghelper to the installed tools

---

README.md

Update the README so those looking for reusable actions are also pointed towards the `.github` repository in case they stumble upon this first.

docs: update readme to point to .github repo

---

chainlink-testing-framework/build-image/action.yml
chainlink-testing-framework/run-tests/action.yml

This is needed for https://smartcontract-it.atlassian.net/browse/TT-1049 and https://github.com/smartcontractkit/chainlink/pull/12835

Allow to pass go coverage flags to "build chainlink image" and "run test" steps

---

chainlink-testing-framework/setup-run-tests-environment/action.yml

modify `chainlink-testing-framework/setup-run-tests-environment/action.yml` to receive a `no-cache` input and pass it along to `chainlink-testing-framework/setup-go/action.yml`

chore setup-run-tests-env no-cache

---

chainlink-testing-framework/run-tests/action.yml

modify `chainlink-testing-framework/run-tests/action.yml` to have `no-cache` input and pass it along to `chainlink-testing-framework/setup-run-tests-environment/action.yml`

chore modifye run-tests add no-cache input

---

.github/workflows/sync-github-app-token-issuer.yaml
chainlink-testing-framework/build-image/action.yml
chainlink-testing-framework/setup-run-tests-environment/action.yml
docker/build-push/action.yml
docker/image-exists/action.yml

Setting `mask-aws-account-id: true` for all usages of `aws-actions/configure-aws-credentials.
Typically secrets are an ARN which include the account id, but the account id itself won't be masked by default. To minimize leaking them using this flag will also mask the account id.
---
RE-2443

chore: mask aws account id

---

chainlink-testing-framework/run-tests/action.yml
chainlink-testing-framework/setup-go/action.yml
chainlink-testing-framework/setup-run-tests-environment/action.yml

- Add `cache_builds` input to optionally cache golang builds based on `go env GOCACHE` 
- Use `go env GOMODCACHE` to cache golang mods
- Clean up order of inputs and actions

Update chainlink-testing-framework/setup-go and chainlink-testing-framework/run-tests actions

---

chainlink-testing-framework/run-tests/action.yml

1. Add test_config_override_path to support config by path (required for CCIP tests in core)
2. Remove test secrets and test inputs. They will be provided as env vars to the action and composed by `ReadFromEnvVar()` in test configs

Update run-tests action
